# PostgreSQL
#   gem install pg
#
#   Ensure the PostgreSQL gem is defined in your Gemfile
#   gem 'pg'
default: &default
  adapter: postgresql
  encoding: unicode
  username: rails_pg
  password: pg_rails_local
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  adapter: postgresql
  encoding: unicode
  database: alphablog_development
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: rails_pg
  password: pg_rails_local

test:
  <<: *default
  database: alphablog_test

production:
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>
  pool: 2
